### ISSUE TITLE
How to change segment positions ? 

### ISSUE THREAD

**Issue by salmanfarisvp** [UnexpectedMaker/Neo7Segment#3]
Hi,

First of all thank for the library, and I would like to know how we can change the segment positions into a different mode like

---5
-4 --6
---3
-0---2
---1

Thanks.

**Comment by SupremeSports** [comment]
Bytes would need to be reassigned in Neo7Segment.cpp

**Comment by UnexpectedMaker** [comment]
Or if it's a permanent change, you can change them, in the Neo7Segment.h array.

**Comment by salmanfarisvp** [comment]
Thanks @SupremeSports  and @UnexpectedMaker, I created one.  https://github.com/salmanfarisvp/NeoClock/blob/master/main.ino
